package pl.polsl.settings;

public enum Extension {
	BUS_CONNECTION,
	ACCUMULATOR_MODIFIERS,
	ALU_LOGICAL_OPERATIONS,
	ALU_ARITHMETIC_OPERATIONS,
	STACK,
	DATA_REGISTER_X,
	DATA_REGISTER_Y,
	INPUT_OUTPUT,
	FLAGS
}
