USE sssebuss_bd;

DROP TABLE IF EXISTS Categories CASCADE;
DROP TABLE IF EXISTS Reply CASCADE;
DROP TABLE IF EXISTS Topics CASCADE;
DROP TABLE IF EXISTS User CASCADE;

CREATE TABLE Categories
(
	categoryID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	categoryName VARCHAR(50) NOT NULL,
	PRIMARY KEY (categoryID)

) ;


CREATE TABLE Reply
(
	replyID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	userID BIGINT UNSIGNED NOT NULL,
	topicID BIGINT UNSIGNED NOT NULL,
	replyText TEXT NOT NULL,
	PRIMARY KEY (replyID),
	KEY (topicID),
	KEY (userID)

) ;


CREATE TABLE Topics
(
	topicID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	userID BIGINT UNSIGNED NOT NULL,
	categoryID BIGINT UNSIGNED NOT NULL,
	topicName VARCHAR(50) NOT NULL,
	PRIMARY KEY (topicID),
	KEY (categoryID)

) ;


CREATE TABLE User
(
	userID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	login VARCHAR(30) NOT NULL,
	password VARCHAR(64) NOT NULL,
	emailAddress VARCHAR(30) NOT NULL,
	PRIMARY KEY (userID)

) ;





ALTER TABLE Reply ADD CONSTRAINT FK_Reply_Topics 
	FOREIGN KEY (topicID) REFERENCES Topics (topicID);

ALTER TABLE Reply ADD CONSTRAINT FK_Reply_User 
	FOREIGN KEY (userID) REFERENCES User (userID);

ALTER TABLE Topics ADD CONSTRAINT FK_Topics_Categories 
	FOREIGN KEY (categoryID) REFERENCES Categories (categoryID);

ALTER TABLE Topics ADD CONSTRAINT FK_Topics_User 
	FOREIGN KEY (topicID) REFERENCES User (userID);
