

DROP TABLE IF EXISTS Categories CASCADE
;
DROP TABLE IF EXISTS Reply CASCADE
;
DROP TABLE IF EXISTS Topics CASCADE
;
DROP TABLE IF EXISTS Users CASCADE
;

CREATE TABLE Categories
(
	categoryID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	categoryName VARCHAR(50) NOT NULL,
	PRIMARY KEY (categoryID)

) 
;


CREATE TABLE Reply
(
	replyID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	userID BIGINT UNSIGNED NOT NULL,
	topicID BIGINT UNSIGNED NOT NULL,
	replyText TEXT NOT NULL,
	date DATETIME NOT NULL,
	PRIMARY KEY (replyID)

) 
;


CREATE TABLE Topics
(
	topicID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	userID BIGINT UNSIGNED NOT NULL,
	categoryID BIGINT UNSIGNED NOT NULL,
	topicName VARCHAR(50) NOT NULL,
	date DATETIME NOT NULL,
	PRIMARY KEY (topicID)

) 
;


CREATE TABLE Users
(
	userID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	login VARCHAR(30) NOT NULL,
	password VARCHAR(64) NOT NULL,
	emailAddress VARCHAR(30) NOT NULL,
	PRIMARY KEY (userID)

) 
;
